/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dinhnn' at '3/27/17 9:26 PM' with Gradle 2.13
 *
 * @author dinhnn, @date 3/27/17 9:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
